"""added password field to developer

Revision ID: 16197d038c4e
Revises: 6c86e9cf82fa
Create Date: 2026-04-04 23:41:08.090679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16197d038c4e'
down_revision: Union[str, Sequence[str], None] = '6c86e9cf82fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'hashed_password')
    # ### end Alembic commands ###
